

services:
  postgres:
    image: postgres:15
    container_name: weather_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  producer:
    build: ./producer
    container_name: weather_producer
    restart: always

  consumer:
    build: ./consumer
    container_name: weather_consumer
    depends_on:
      - postgres
    restart: always

  grafana:
    image: grafana/grafana
    container_name: weather_grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
